### ISSUE TITLE
Support for other data types

### ISSUE THREAD

**Issue by PKWadsy** [PKWadsy/kint#6]
Currently, Kint only allows support for JSON bodies and responses because it uses zod parsing. This is extremely limiting. It should support raw text and other data types.

**Comment by joshuabrownenz** [comment]
I think this could be also be handled with middleware/postware?? I don't know if that is a thing. And then have the default implementation use JSON. I don't know how type parsing would work though

Another option would be to have a serializer as an optional argument to the `makeEndpoint` function. Defaulting to using JSON.  However that will require careful type validation to make sure Zod middleware/validation will not be applied and/or not fail depending on the output type

**Comment by PKWadsy** [comment]
With the new architecture, I think this is no longer necessary. The raw request is now passed through and valid data passed in through the context if validators are used.

**Comment by PKWadsy** [comment]
With the new architecture, I think this is no longer necessary. The raw request is now passed through and valid data passed in through the context if validators are used.
