### ISSUE TITLE
Use Codecov.io

### ISSUE THREAD

**Issue by PKWadsy** [PKWadsy/kint#9]
I would recommend using codecov.io to provide commit, branch and PR diff coverage targets.

_Originally posted by @joshuabrownenz in https://github.com/PKWadsy/kint/issues/7#issuecomment-2062831218_

**Comment by joshuabrownenz** [comment]
I'm happy to implement this and setup the testing pipeline

**Comment by joshuabrownenz** [comment]
@PKWadsy Actually it might be better is this was handled under or account on codecov.io. I will replace myself as the assignee
